
package com.evry.fs.payment.ems.srv.ws.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.evry.fs.payment.ems.AddEmployeeRequestType;
import com.evry.fs.payment.ems.AddEmployeeResponseType;
import com.evry.fs.payment.ems.CheckLoginRequestType;
import com.evry.fs.payment.ems.CheckLoginResponseType;
import com.evry.fs.payment.ems.DeleteEmployeeRequestType;
import com.evry.fs.payment.ems.DeleteEmployeeResponseType;
import com.evry.fs.payment.ems.GetAllEmployeesInProjectRequestType;
import com.evry.fs.payment.ems.GetAllEmployeesInProjectResponseType;
import com.evry.fs.payment.ems.GetAllEmployeesRequestType;
import com.evry.fs.payment.ems.GetAllEmployeesResponseType;
import com.evry.fs.payment.ems.GetAllFreeResourcesRequestType;
import com.evry.fs.payment.ems.GetAllFreeResourcesResponseType;
import com.evry.fs.payment.ems.GetEmployeeInfoRequestType;
import com.evry.fs.payment.ems.GetEmployeeInfoResponseType;
import com.evry.fs.payment.ems.ObjectFactory;
import com.evry.fs.payment.ems.UpdateEmployeeRequestType;
import com.evry.fs.payment.ems.UpdateEmployeeResponseType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeeService_V19_1", targetNamespace = "http://evry.com/fs/payment/ems/services/EmployeeService_V19_1/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeServiceV191 {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.evry.fs.payment.ems.GetEmployeeInfoResponseType
     */
    @WebMethod(action = "http://evry.com/fs/payment/ems/services/EmployeeService_V19_1/getEmployeesInfo")
    @WebResult(name = "getEmployeeInfoResponseType", targetNamespace = "http://evry.com/fs/payment/ems", partName = "parameters")
    public GetEmployeeInfoResponseType getEmployeeInfo(
        @WebParam(name = "getEmployeeInfoRequestType", targetNamespace = "http://evry.com/fs/payment/ems", partName = "parameters")
        GetEmployeeInfoRequestType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.evry.fs.payment.ems.CheckLoginResponseType
     */
    @WebMethod(action = "http://evry.com/fs/payment/ems/services/EmployeeService_V19_1/checkLogin")
    @WebResult(name = "checkLoginResponseType", targetNamespace = "http://evry.com/fs/payment/ems", partName = "parameters")
    public CheckLoginResponseType checkLogin(
        @WebParam(name = "checkLoginRequestType", targetNamespace = "http://evry.com/fs/payment/ems", partName = "parameters")
        CheckLoginRequestType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.evry.fs.payment.ems.DeleteEmployeeResponseType
     */
    @WebMethod(action = "http://evry.com/fs/payment/ems/services/EmployeeService_V19_1/deleteEmployee")
    @WebResult(name = "deleteEmployeeResponseType", targetNamespace = "http://evry.com/fs/payment/ems", partName = "parameters")
    public DeleteEmployeeResponseType deleteEmployee(
        @WebParam(name = "deleteEmployeeRequestType", targetNamespace = "http://evry.com/fs/payment/ems", partName = "parameters")
        DeleteEmployeeRequestType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.evry.fs.payment.ems.GetAllEmployeesInProjectResponseType
     */
    @WebMethod(action = "http://evry.com/fs/payment/ems/services/EmployeeService_V19_1/getAllEmployeesInProject")
    @WebResult(name = "getAllEmployeesInProjectResponseType", targetNamespace = "http://evry.com/fs/payment/ems", partName = "parameters")
    public GetAllEmployeesInProjectResponseType getAllEmployeesInProject(
        @WebParam(name = "getAllEmployeesInProjectRequestType", targetNamespace = "http://evry.com/fs/payment/ems", partName = "parameters")
        GetAllEmployeesInProjectRequestType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.evry.fs.payment.ems.AddEmployeeResponseType
     */
    @WebMethod(action = "http://evry.com/fs/payment/ems/services/EmployeeService_V19_1/addEmployee")
    @WebResult(name = "addEmployeeResponseType", targetNamespace = "http://evry.com/fs/payment/ems", partName = "parameters")
    public AddEmployeeResponseType addEmployee(
        @WebParam(name = "addEmployeeRequestType", targetNamespace = "http://evry.com/fs/payment/ems", partName = "parameters")
        AddEmployeeRequestType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.evry.fs.payment.ems.GetAllEmployeesResponseType
     */
    @WebMethod(action = "http://evry.com/fs/payment/ems/services/EmployeeService_V19_1/getAllEmployees")
    @WebResult(name = "getAllEmployeesResponseType", targetNamespace = "http://evry.com/fs/payment/ems", partName = "parameters")
    public GetAllEmployeesResponseType getAllEmployees(
        @WebParam(name = "getAllEmployeesRequestType", targetNamespace = "http://evry.com/fs/payment/ems", partName = "parameters")
        GetAllEmployeesRequestType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.evry.fs.payment.ems.GetAllFreeResourcesResponseType
     */
    @WebMethod(action = "http://evry.com/fs/payment/ems/services/EmployeeService_V19_1/getAllFreeResources")
    @WebResult(name = "getAllFreeResourcesResponseType", targetNamespace = "http://evry.com/fs/payment/ems", partName = "parameters")
    public GetAllFreeResourcesResponseType getAllFreeResources(
        @WebParam(name = "getAllFreeResourcesRequestType", targetNamespace = "http://evry.com/fs/payment/ems", partName = "parameters")
        GetAllFreeResourcesRequestType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.evry.fs.payment.ems.UpdateEmployeeResponseType
     */
    @WebMethod(action = "http://evry.com/fs/payment/ems/services/EmployeeService_V19_1/updateEmployee")
    @WebResult(name = "updateEmployeeResponseType", targetNamespace = "http://evry.com/fs/payment/ems", partName = "parameters")
    public UpdateEmployeeResponseType updateEmployee(
        @WebParam(name = "updateEmployeeRequestType", targetNamespace = "http://evry.com/fs/payment/ems", partName = "parameters")
        UpdateEmployeeRequestType parameters);

}
