
package com.evry.fs.payment.pms.srv.ws.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProjectServiceV191ImplService", targetNamespace = "http://service.ws.srv.pms.payment.fs.evry.com/", wsdlLocation = "http://localhost:3456/pms-srv-ws/services/pmsservice/projectServiceV191?wsdl")
public class ProjectServiceV191ImplService
    extends Service
{

    private final static URL PROJECTSERVICEV191IMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PROJECTSERVICEV191IMPLSERVICE_EXCEPTION;
    private final static QName PROJECTSERVICEV191IMPLSERVICE_QNAME = new QName("http://service.ws.srv.pms.payment.fs.evry.com/", "ProjectServiceV191ImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:3456/pms-srv-ws/services/pmsservice/projectServiceV191?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROJECTSERVICEV191IMPLSERVICE_WSDL_LOCATION = url;
        PROJECTSERVICEV191IMPLSERVICE_EXCEPTION = e;
    }

    public ProjectServiceV191ImplService() {
        super(__getWsdlLocation(), PROJECTSERVICEV191IMPLSERVICE_QNAME);
    }

    public ProjectServiceV191ImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROJECTSERVICEV191IMPLSERVICE_QNAME, features);
    }

    public ProjectServiceV191ImplService(URL wsdlLocation) {
        super(wsdlLocation, PROJECTSERVICEV191IMPLSERVICE_QNAME);
    }

    public ProjectServiceV191ImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROJECTSERVICEV191IMPLSERVICE_QNAME, features);
    }

    public ProjectServiceV191ImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProjectServiceV191ImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProjectServiceV191
     */
    @WebEndpoint(name = "ProjectServiceV191ImplPort")
    public ProjectServiceV191 getProjectServiceV191ImplPort() {
        return super.getPort(new QName("http://service.ws.srv.pms.payment.fs.evry.com/", "ProjectServiceV191ImplPort"), ProjectServiceV191.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProjectServiceV191
     */
    @WebEndpoint(name = "ProjectServiceV191ImplPort")
    public ProjectServiceV191 getProjectServiceV191ImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.ws.srv.pms.payment.fs.evry.com/", "ProjectServiceV191ImplPort"), ProjectServiceV191.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROJECTSERVICEV191IMPLSERVICE_EXCEPTION!= null) {
            throw PROJECTSERVICEV191IMPLSERVICE_EXCEPTION;
        }
        return PROJECTSERVICEV191IMPLSERVICE_WSDL_LOCATION;
    }

}
