
package com.evry.fs.payment.pms.srv.ws.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.evry.fs.payment.pms.AddProjectRequestType;
import com.evry.fs.payment.pms.AddProjectResponseType;
import com.evry.fs.payment.pms.DeleteProjectRequestType;
import com.evry.fs.payment.pms.DeleteProjectResponseType;
import com.evry.fs.payment.pms.GetAllProjectsRequestType;
import com.evry.fs.payment.pms.GetAllProjectsResponseType;
import com.evry.fs.payment.pms.GetProjectInfoRequestType;
import com.evry.fs.payment.pms.GetProjectInfoResponseType;
import com.evry.fs.payment.pms.ObjectFactory;
import com.evry.fs.payment.pms.UpdateProjectRequestType;
import com.evry.fs.payment.pms.UpdateProjectResponseType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProjectService_V19_1", targetNamespace = "http://evry.com/fs/payment/pms/services/ProjectService_V19_1/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProjectServiceV191 {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.evry.fs.payment.pms.AddProjectResponseType
     */
    @WebMethod(action = "http://www.example.org/ProjectService_V19_1/addProject")
    @WebResult(name = "addProjectResponseType", targetNamespace = "http://evry.com/fs/payment/pms", partName = "parameters")
    public AddProjectResponseType addProject(
        @WebParam(name = "addProjectRequestType", targetNamespace = "http://evry.com/fs/payment/pms", partName = "parameters")
        AddProjectRequestType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.evry.fs.payment.pms.DeleteProjectResponseType
     */
    @WebMethod(action = "http://evry.com/fs/payment/pms/services/ProjectService_V19_1/deleteProject")
    @WebResult(name = "deleteProjectResponseType", targetNamespace = "http://evry.com/fs/payment/pms", partName = "parameters")
    public DeleteProjectResponseType deleteProject(
        @WebParam(name = "deleteProjectRequestType", targetNamespace = "http://evry.com/fs/payment/pms", partName = "parameters")
        DeleteProjectRequestType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.evry.fs.payment.pms.GetProjectInfoResponseType
     */
    @WebMethod(action = "http://evry.com/fs/payment/pms/services/ProjectService_V19_1/getProjectInfo")
    @WebResult(name = "getProjectInfoResponseType", targetNamespace = "http://evry.com/fs/payment/pms", partName = "parameters")
    public GetProjectInfoResponseType getProjectInfo(
        @WebParam(name = "getProjectInfoRequestType", targetNamespace = "http://evry.com/fs/payment/pms", partName = "parameters")
        GetProjectInfoRequestType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.evry.fs.payment.pms.UpdateProjectResponseType
     */
    @WebMethod(action = "http://evry.com/fs/payment/pms/services/ProjectService_V19_1/updateProject")
    @WebResult(name = "updateProjectResponseType", targetNamespace = "http://evry.com/fs/payment/pms", partName = "parameters")
    public UpdateProjectResponseType updateProject(
        @WebParam(name = "updateProjectRequestType", targetNamespace = "http://evry.com/fs/payment/pms", partName = "parameters")
        UpdateProjectRequestType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.evry.fs.payment.pms.GetAllProjectsResponseType
     */
    @WebMethod(action = "http://evry.com/fs/payment/pms/services/ProjectService_V19_1/getAllProjects")
    @WebResult(name = "getAllProjectsResponseType", targetNamespace = "http://evry.com/fs/payment/pms", partName = "parameters")
    public GetAllProjectsResponseType getAllProjects(
        @WebParam(name = "getAllProjectsRequestType", targetNamespace = "http://evry.com/fs/payment/pms", partName = "parameters")
        GetAllProjectsRequestType parameters);

}
